linters:
  disable-all: true
  enable:
    # - bodyclose
    # - deadcode
    # - depguard
    # - dogsled
    # - dupl
    # - errcheck
    # - funlen
    # - gochecknoglobals
    # - gochecknoinits
    # - gocognit
    # - goconst
    # - gocritic
    - gocyclo
    # - godox
    # - gofmt
    # - goimports
    # - golint
    # - gomnd
    # - goprintffuncname
    # - gosec
    # - gosimple
    # - govet
    # - ineffassign
    # - interfacer
    # - lll
    # - maligned
    # - misspell
    # - nakedret
    # - prealloc
    # - rowserrcheck
    # - scopelint
    # - staticcheck
    # - structcheck
    # - stylecheck
    # - typecheck
    # - unconvert
    # - unparam
    # - unused
    # - varcheck
    # - whitespace
    # - wsl

linters-settings:
  gocyclo:
    min-complexity: 18

run:
  skip-dirs:
    - testdata
    - helm
    - config-example

service:
  golangci-lint-version: 1.23.8
