project_name: flottbot

before:
  hooks:
    - go mod download

builds:
  - binary: flottbot

    main: ./cmd/flottbot/main.go
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
      - GOPROXY=https://gocenter.io
    flags:
      - -a
    ldflags:
      - -s -w -X github.com/target/flottbot/version.Version={{.Version}} -X github.com/target/flottbot/version.GitHash={{.FullCommit}}

    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs"
      - "^test"
      - Merge pull request
      - Merge branch

archives:
  - id: traefik
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE

checksum:
  name_template: "{{ .ProjectName }}-checksums.txt"
