#!/bin/bash -xe
DOCKER_PATH=$(echo $DOCKERFILE_PATH | sed -e 's/.*\///g')

docker build \
    --build-arg "SOURCE_BRANCH=$SOURCE_BRANCH" \
    --build-arg "SOURCE_COMMIT=$SOURCE_COMMIT" \
    -f $DOCKER_PATH \
    -t $IMAGE_NAME ../
