# name of the action
name: build

# trigger on pull_request or push events
on:
  pull_request:
  push:

permissions:
  contents: read

# pipeline to execute
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: clone
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: install go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          # use version from go.mod file
          go-version-file: 'go.mod'
          cache: true
          check-latest: true

      - name: build
        run: |
          make build
